- name: try to determine carbon host ip address if it is not defined
  set_fact:
      carbon_host: "{{ hostvars[groups[collectd_grafana_group_search_prefix + '-grafana-hosts'][0]]['ansible_default_ipv4']['address']}}"
  when: carbon_host is not defined

- name: check carbon_host ip address variable
  debug: var=carbon_host

- name: download collectd
  command: bash -c "cd /root && wget http://64.22.71.87/collectd_5.4.1-2_amd64.deb" creates=/root/collectd_5.4.1-2_amd64.deb

- shell: bash -c "dpkg -l collectd 2>&1; true"
  register: collectd

- name: setup libsnmp-dev
  apt: name=libsnmp-dev state=present

- name: install collectd
  command: dpkg -i /root/collectd_5.4.1-2_amd64.deb
  when: collectd.stdout.find('5.4.1-2') == -1

- name: put collectd config file
  template: src=collectd/collectd.conf dest=/opt/collectd/etc/collectd{% if collectd_suffix|default("") != "" %}-{{ collectd_suffix }}{% endif %}.conf owner=root group=root mode=0644
  notify:
  - restart collectd

- name: put collectd types DB
  template: src=collectd/types.db dest=/opt/collectd/share/collectd/types.db owner=root group=root mode=0644
  notify:
  - restart collectd

- name: remove supervisord config if exists
  file: name=/etc/supervisor/conf.d/collectd.conf state=absent
  notify:
  - restart supervisor
  - restart collectd

- name: setup snmp
  apt: name=snmp state=present

- name: put collectd eye descriptor
  template: src=collectd/collectd-eye.rb dest=/etc/eye/collectd{% if collectd_suffix|default("") != "" %}-{{ collectd_suffix }}{% endif %}.rb owner=root group=root mode=0644
  when: "not ((ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>'))))"

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  become: yes
  when: "not ((ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>'))))"

- name: put systemd unit file to its destination
  template: src=collectd.service dest=/etc/systemd/system/collectd{% if collectd_suffix|default("") != "" %}-{{ collectd_suffix }}{% endif %}.service owner=root group=root mode=0644
  when: "(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>')))"

- name: enable collectd service
  service: name=collectd{% if collectd_suffix|default("") != "" %}-{{ collectd_suffix }}{% endif %} enabled=yes state=started
  when: "(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>')))"
